# Generated by Django 3.2 on 2022-07-30 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0003_reviewmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogModel',
        ),
        migrations.DeleteModel(
            name='SampleModel',
        ),
        migrations.AlterField(
            model_name='reviewmodel',
            name='evaluation',
            field=models.CharField(choices=[('良い', '良い'), ('悪い', '悪い')], max_length=10),
        ),
    ]
